import json
from pathlib import Path

# This script expands the existing industry-tools.json to meet targets and
# writes the output so each tool object is a single-line JSON object for
# compact viewing.

base_path = Path(__file__).resolve().parents[1] / 'data' / 'industry-tools.json'
backup_path = base_path.with_suffix('.autogen2.bak')

with base_path.open('r', encoding='utf-8') as f:
    data = json.load(f)

categories = data.get('categories', [])
cat_count = len(categories)
total_tools = sum(len(c.get('tools', [])) for c in categories)

# new targets requested by user
TARGET_CATS = 200
TARGET_TOOLS = 5000

# determine next generated index
next_cat_index = 1
for c in categories:
    cid = c.get('id', '')
    if cid.startswith('generated-category-'):
        try:
            n = int(cid.split('-')[-1])
            if n >= next_cat_index:
                next_cat_index = n + 1
        except:
            pass

# backup current file
with backup_path.open('w', encoding='utf-8') as f:
    json.dump({'categories': categories}, f, indent=2, ensure_ascii=False)

# generate until meet targets
while cat_count < TARGET_CATS or total_tools < TARGET_TOOLS:
    cid = f'generated-category-{next_cat_index}'
    display = f'Generated Category {next_cat_index}'
    tools = []

    remaining_tools = TARGET_TOOLS - total_tools
    remaining_cats = max(1, TARGET_CATS - cat_count)
    per_cat = max(1, remaining_tools // remaining_cats)
    # cap per category to a reasonable number to avoid huge single categories
    if per_cat > 200:
        per_cat = 200

    for i in range(1, per_cat + 1):
        tool = {
            'name': f'GeneratedTool {next_cat_index}-{i}',
            'officialUrl': f'https://example.com/generated/{next_cat_index}/{i}',
            'description': 'Autogenerated placeholder tool entry (expand later)',
            'tags': ['generated']
        }
        tools.append(tool)

    categories.append({'id': cid, 'displayName': display, 'tools': tools})
    cat_count += 1
    total_tools += len(tools)
    next_cat_index += 1

# write out with each tool object on a single line
with base_path.open('w', encoding='utf-8') as f:
    f.write('{' + '\n')
    f.write('  "categories": [' + '\n')
    for ci, c in enumerate(categories):
        f.write('    {' + '\n')
        f.write(f'      "id": {json.dumps(c["id"])},\n')
        f.write(f'      "displayName": {json.dumps(c["displayName"])},\n')
        f.write('      "tools": [' + '\n')
        for ti, t in enumerate(c.get('tools', [])):
            # compact tool as single line
            tool_json = json.dumps(t, ensure_ascii=False, separators=(', ', ': '))
            f.write(f'        {tool_json}')
            if ti < len(c.get('tools', [])) - 1:
                f.write(',\n')
            else:
                f.write('\n')
        f.write('      ]\n')
        if ci < len(categories) - 1:
            f.write('    },\n')
        else:
            f.write('    }\n')
    f.write('  ]\n')
    f.write('}\n')

print('WROTE:', base_path)
print('Categories:', cat_count)
print('Total Tools:', total_tools)
print('Backup path:', backup_path)
